{% set data = load_setup_py_data() %}

package:
  name: openalea.core
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install 

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
    - six
  run:
    - python  <3.11
    - ipykernel
    - configobj
    - six

test:
  imports:
    - openalea.core
  requires:
    - pytest
  source_files:
    - test/
    - test/*.py

  commands:
    - cd test
    - pytest -v test_*.py

about:
  home: {{ data.get('url') }}
  license: Cecill-c License
  summary: {{ data.get('description') }}

