{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ GIT_DESCRIBE_TAG  | replace("v", "") }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{PYTHON}} -m pip install . -vv

requirements:
  build:
    - python {{ pyproject["project"]["requires-python"] }}
    {% for dep in pyproject["build-system"]["requires"] %}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    - python {{ pyproject["project"]["requires-python"] }}
    {% for dep in pyproject["project"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in pyproject["tool"]["conda"]["environment"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    - pytest
  imports:
    - openalea.core
  source_files:
    - test/**
    - test/data/**
  commands:
    - cd test
    - pytest -v test_*.py

about:
  summary: {{ pyproject["project"]["description"] }}
  license: {{ pyproject["project"]["license"] }}
  home: {{ pyproject["project"]["urls"]["Homepage"] }}
