name: build_publish_anaconda

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'


jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@label
    with:
      operating-system: '["ubuntu-latest"]'
      build-options: ""
      label: latest
      python-minor-version:  "[12]"
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
